self-hosted-runner:
  # Custom labels of self-hosted or large GitHub hosted runners
  # so that actionlint knows that they are not a typo
  labels:
    - 4-core-16-ram-150-hdd
    - 8-core-32-ram-300-hdd
    - arm-ubuntu-medium
    - arm-ubuntu-large
    - arm-ubuntu-xlarge
# Configuration variables in array of strings defined in your repository or
# organization. `null` means disabling configuration variables check.
# Empty array means no configuration variable is allowed.
config-variables: null
